version: "3"

services:

  server:
    container_name: server
    image: nginx:1.23
    volumes:
      - ./:/var/www
      - ./_docker/nginx/conf.d/:/etc/nginx/conf.d
    ports:
      - "8000:80"
    restart: always

  app:
    container_name: app
    build:
      context: .
      dockerfile: _docker/app/Dockerfile
    volumes:
      - ./_docker/app/php.ini:/usr/local/etc/php/php.ini
    depends_on:
      - server
      - database

  database:
    container_name: database
    hostname: ${DB_HOST}
    env_file:
      - .env
    ports:
      - "8001:${DB_PORT}"

    # -----MySQL-----
    image: mysql:8.0
    volumes:
      - ./_docker/tmp/db:/var/lib/mysqld
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: root
    # -----End MySQL-----

    # -----PostgreSQL-----
#    image: postgres:15.0
#    volumes:
#      - ./_docker/tmp/db:/var/lib/postgresql/data
#    environment:
#      POSTGRES_DB: ${DB_DATABASE}
#      POSTGRES_USER: ${DB_USERNAME}
#      POSTGRES_PASSWORD: ${DB_PASSWORD}
    # -----End PostgreSQL-----

    restart: always

  adminer:
    container_name: adminer
    image: adminer
    depends_on:
      - database
    restart: always
    ports:
      - "8002:8080"